Vagrant.configure("2") do |config|
  config.vm.define "node" do |node|
    node.ssh.insert_key = false
    node.vm.box = "bento/centos-7.6"
    node.vm.box_version = "201907.24.0"
    node.vm.hostname = "node"
    node.vm.network "private_network", ip: "192.168.3.33"
    node.vm.provider "virtualbox" do |v|
      v.memory = 2000
      v.cpus = 1
      v.name = "node"
    end
    # 一对默认的秘钥，有需要可以自己重新生成一对
    node.vm.provision "file", source: "id_rsa.pub", destination: "~/.ssh/id_rsa.pub"
    # node.vm.provision "file", source: "id_rsa", destination: "~/.ssh/id_rsa"
    node.vm.provision "shell", path: "install.sh", privileged: false
    node.vm.synced_folder "./", "/home/vagrant/node_start",  create: true
    # node.vm.synced_folder "D:/", "/home/vagrant/d"
  end
end
