name: pubsh

# 只在master分支有push的时候，进行构建和发布
on: 
  push:
    branches: master

env:
  GIT_USER: cenzhipeng
  CURRENT_BRANCH: master
  USE_SSH: false

jobs:
  build-publish:

    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
            node-version: '10.x'
      - name: install yarn
        run: npm install yarn
      - name: install docusaurus
        run: yarn global add docusaurus-init

      - name: build and publish
        working-directory: ./website
        run: yarn run publish-gh-pages
