name: publish

# 只在master分支有push的时候，进行构建和发布
on: 
  push:
    branches: master

env:
  GIT_USER: cenzhipeng
  CURRENT_BRANCH: master
  USE_SSH: false
  CUSTOM_DOMAIN: cenzhipeng.com

jobs:
  build-publish:

    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
            node-version: '10.x'
      - name: config git
        run:  |
          git config --global user.email "cenzhipeng@aliyun.com"
          git config --global user.name "cenzhipeng"
      - name: install yarn
        run: npm install yarn
      - name: install dependencies
        run: yarn install
        working-directory: ./website
      - name: build and publish
        working-directory: ./website
        run: |
          echo "machine github.com login ${GIT_USER} password ${{ secrets.GT_TOKEN }}" > ~/.netrc
          yarn run publish-gh-pages
      - name: change language && and robots.txt && modify js cdn
        run: |
          git checkout gh-pages
          git stash
          git pull
          bash custom_config.sh
          git add ./robots.txt
          find .  -iname "*.html" |grep -v /en/ | xargs git add
          git commit -m "Deploy website"
          git push



