name: publish

# 只在master分支有push的时候，进行构建和发布
on: 
  push:
    branches: master

env:
  GIT_USER: cenzhipeng
  CURRENT_BRANCH: master
  USE_SSH: false
  CUSTOM_DOMAIN: cenzhipeng.com

jobs:
  build-publish:

    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
            node-version: '10.x'
      - name: config git
        run:  |
          git config --global user.email "cenzhipeng@aliyun.com"
          git config --global user.name "cenzhipeng"
      - name: install yarn
        run: npm install yarn
      - name: install dependencies
        run: yarn install
      - name: build and publish
        run: |
          echo "machine github.com login ${GIT_USER} password ${{ secrets.GT_TOKEN }}" > ~/.netrc
          yarn run publish-gh-pages
      - name: change language && and robots.txt && modify js cdn
        run: |
          git stash
          git checkout gh-pages
          git pull
          wget https://raw.githubusercontent.com/cenzhipeng/knowledge-base/master/custom_config.sh
          bash custom_config.sh
          rm -rf custom_config.sh
          git add ./robots.txt
          find .  -iname "*.html" |grep -v /en/ | xargs git add
          git commit -m "Deploy website"
          git push
      - name: push index to algolia
        run: |
          git checkout master
          # sudo apt-get update -y
          # sudo apt-get install -y jq
          docker run -it \
          -e APPLICATION_ID=QY49S75304 \
          -e API_KEY=${{ secrets.GT_TOKEN }}  \
          -e "CONFIG=$(cat ./algolia-config.json | jq -r tostring)" \
          algolia/docsearch-scraper
          docker run -it \
          -e APPLICATION_ID=QY49S75304 \
          -e API_KEY=${{ secrets.GT_TOKEN }}  \
          -e "CONFIG=$(cat ./algolia-config-another.json | jq -r tostring)" \
          algolia/docsearch-scraper



